function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  F2431 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  F2431 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  f2431 = importfile("F:\IEEE Sensors 2021\scripts\data\sensor measurement June 24 2021\Benthowave Experiments\f2431.txt", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Jun-2021 01:53:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["FreqHz", "Ch0MagdB", "Ch0Phasecyc", "Ch1MagdB", "Ch1Phasecyc", "Ch2MagdB", "Ch2Phasecyc", "Ch3MagdB", "Ch3Phasecyc"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["FreqHz", "Ch0MagdB", "Ch0Phasecyc", "Ch1MagdB", "Ch1Phasecyc", "Ch2MagdB", "Ch2Phasecyc", "Ch3MagdB", "Ch3Phasecyc"], "ThousandsSeparator", ",");

% Import the data
data = readtable(filename, opts);

end